//go:build !docs
// +build !docs

package cmd

import (
	"context"
	"crypto/sha1"
	"os"
	"path/filepath"
	"testing"

	"github.com/hyperledger/firefly-common/pkg/config"
	"github.com/stretchr/testify/assert"
)

func TestConfigDocsUpToDate(t *testing.T) {
	// Initialize config of all plugins
	initConfig()
	generatedConfig, err := config.GenerateConfigMarkdown(context.Background(), "", config.GetKnownKeys())
	assert.NoError(t, err)
	configOnDisk, err := os.ReadFile(filepath.Join("..", "config.md"))
	assert.NoError(t, err)

	generatedConfigHash := sha1.New()
	generatedConfigHash.Write(generatedConfig)
	configOnDiskHash := sha1.New()
	configOnDiskHash.Write(configOnDisk)
	assert.Equal(t, configOnDiskHash.Sum(nil), generatedConfigHash.Sum(nil), "The config reference docs generated by the code did not match the config.md file in git. Did you forget to run `make docs`?")
}
